### ISSUE TITLE
Escaping is not seemed to work properly

### ISSUE THREAD

**Issue by MJ-DEV91** [JSONPath-Plus/JSONPath#137]
Hi. There's a field inside the JSON which contains '@', and now I want to escape it. 
Assume below JSON:
```json
{
    "id": "1234",
    "items": [
        {
            "id": "i123",
            "item": {
                "id": "789",
                "@type": "Person",
                "name": "Find me!!"
            }
        }
    ]
}
```
I wanna access the name (items.item.name) with a Query:
```js
$.items[?(@.item.`@type` === 'Person')].item.name
```
I put `@type` inside the backticks, but it's not working.

If I had "type" instead of "@type", the below query works fine:
```json
{
    "id": "1234",
    "items": [
        {
            "id": "i123",
            "item": {
                "id": "789",
                "type": "Person",
                "name": "Find me!!"
            }
        }
    ]
}
```
```js
$.items[?(@.item.type === 'Person')].item.name
```
```json
[
    "Find me!!"
]
```

- JSONPath-Plus version: [4.0.0]

## Desktop**
 - OS: [ Windows 10]

**Comment by brettz9** [comment]
`$.items[?(@.item['@type'] === 'Person')].item.name` appears to be working for me. In looking at source, it appears that `@` is only manipulated if folowed by any of `.\s)[`.

**Comment by MJ-DEV91** [comment]
> `$.items[?(@.item['@type'] === 'Person')].item.name` appears to be working for me. In looking at source, it appears that `@` is only manipulated if folowed by any of `.\s)[`.

Thank you. it looks like I didn't do it correctly.

**Comment by brettz9** [comment]
We haven't clearly documented it, and we really need a proper parser in the first place to make this all more consistent, e.g., so you could use backticks anywhere. But glad it worked out.
