### ISSUE TITLE
Error installing v5.0.1

### ISSUE THREAD

**Issue by jorisroling** [JSONPath-Plus/JSONPath#144]
## Describe the bug
My npm module contains jsonpath-plus, now when I include my project in another, this pops up:
`Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "dist/index-node-cjs.js" defined in the package config <my project>/package.json; targets must start with "./"`

## Environment (IMPORTANT)
- JSONPath-Plus version: 5.0.1

## Desktop**
 - OS: NodeJS
 - v14.15.4

**Comment by brettz9** [comment]
Apologies--should be fixed in 5.0.2...
