### ISSUE TITLE
Package exports mean node version is always used with Webpack 5

### ISSUE THREAD

**Issue by gjvoosten** [JSONPath-Plus/JSONPath#145]
## Describe the bug

The current `package.json` specifies: https://github.com/JSONPath-Plus/JSONPath/blob/v5.0.2/package.json#L7-L10
which, if I read https://webpack.js.org/guides/package-exports/ correctly, mean the node version is always imported, even in browser mode.

We noticed this change in behaviour when our JSONPath queries were suddenly taking much longer to run after upgrading from v4.0.0 to v5.0.2. A query that would take < 3ms under v4.0.0 was suddenly taking > 100ms under v5.0.2. Replacing `index-node-esm.mjs` with `index-browser-esm.js` would bring the performance back to normal.

**Comment by brettz9** [comment]
From the PR at https://github.com/JSONPath-Plus/JSONPath/pull/146#discussion_r569496321

> Hmm... I've added a comment at [webpack/webpack#11597 (comment)](https://github.com/webpack/webpack/issues/11597#issuecomment-772579321) , as it looks to me that bundlers should not be using `type` for interpretation of non-Node fields. There is a [workaround](https://github.com/webpack/webpack/issues/11597#issuecomment-705114717) there that may work for now without our changing the code, as I really think we should be able to use ".js" with browser ESM while using `type: commonjs` for Node. If we don't hear back in some time, let's file a new Webpack issue.
