### ISSUE TITLE
Standardizing on the escaping of JSON paths

### ISSUE THREAD

**Issue by vongohren** [JSONPath-Plus/JSONPath#164]
## Describe the bug

I feel that JSON path escaping should be the same across libraries

Because in the SSI data exchange world there are certain filters one can use and will struggle to match if libraries use differnt mechnism for escaping.

https://github.com/decentralized-identity/presentation-exchange/issues/278

So why are the most used libraries in the ecosystem, two escaping mechanism different?
https://github.com/dchester/jsonpath#other-minor-differences

### Console error or logs
`TypeError: Unknown value type conte`

## Expected behavior

Be able to call the path on both mentioned libraries

## Environment (IMPORTANT)
- JSONPath-Plus version: [e.g. 4.0.0]

## Desktop**
 - OS: [e.g. Windows]
 - Browser and version [e.g. chrome 65] or Node Version [e.g. 10.2]

**Comment by brettz9** [comment]
Firstly, let me say this project really doesn't currently have a truly active maintainer Barring anyone else to take over the role, I may just merge some PRs if simple enough, and I happen to have the energy.

And for any changes we make, there is a project already underway that is offering a path for standardization; see issue #124 (and the site it references: https://github.com/cburgmer/json-path-comparison ). I suggest you look to see whether your concerns are already being met by their proposals. Any significant PRs to make changes on this project would need to ensure they are consistent with that path.

**Comment by vongohren** [comment]
Thanks for that suggestion I will look into it!
