### ISSUE TITLE
Problem with key that start with @ character

### ISSUE THREAD

**Issue by lOdwrot** [JSONPath-Plus/JSONPath#166]
## Describe the bug

When trying

## Code sample or steps to reproduce
I have following JSON:

```
{
  "Request": {
    "@Domain": "SomeDomain",
    "Vehicle": {
      "@ID": "E11XPD"
    }
  }
}
```
I can execute following jsonpath expression:

`$.Request['@Domain']`

When I want to acces ID by expression:

`$.Request.Vehicle['@ID']`

I have following error: "Unknown value type".

I am using library this way:

```
import { JSONPath } from 'jsonpath-plus';
...
JSONPath({path: pattern, json: resultJson})
```

### Console error or logs

Unknown value type

## Expected behavior

Function will return value under proper key.

## Expected result

I will have a value of node under @ID key (in this case E11XPD)

## Environment (IMPORTANT)
- JSONPath-Plus version: 6.0.1

## Desktop**
 - OS: [Windows]

**Comment by brettz9** [comment]
For jsonpath-plus, you need to escape the at-sign with a backtick ``` ` ```. That should resolve, so closing, though feel free to comment further.
