### ISSUE TITLE
Does the cmdlet work ?

### ISSUE THREAD

**Issue by TheHolyMecca** [JSONPath-Plus/JSONPath#212]
Does the cmdlet work ? 
because can't make work with -bodyparameter or -devicecategory, eveytime he result with an error
`$Params = @{
    DeviceCategory = @{
    "DisplayName" = "$NewCategory"}
} | ConvertTo-Json
try {
    # Changer la category
Update-MgDeviceManagementManagedDevice -ManagedDeviceId $Device -BodyParameter $Params `

_Originally posted by @SamSepiolWarden in https://github.com/microsoft/Intune-PowerShell-SDK/issues/145_

**Comment by brettz9** [comment]
It seems you are not using jsonpath-plus.
