### ISSUE TITLE
Cannot read properties of undefined (reading 'match') on an absent field

### ISSUE THREAD

**Issue by Scratch-net** [JSONPath-Plus/JSONPath#218]
## Describe the bug

This error gets thrown if match field does not exist

## Code sample or steps to reproduce

```js
{
    "items":[
        {
            "name": "John Doe",
            "country": "USA"
        },
        {
          "country": "USA",
          "age":25
        }
    ]
}
```
//fails
`$.items[?(@.name.match(/.*oe/))]`

//only way to make it work
`$.items[?(@.name && @.name.match(/.*oe/))]`

### Console error or logs

Error: jsonPath: Cannot read properties of undefined (reading 'match'): @.name.match(/.*abc/) 

    at JSONPath.Object.<anonymous>.JSONPath._eval
    at JSONPath.Object.<anonymous>.JSONPath._walk
    at JSONPath.Object.<anonymous>.JSONPath._trace
    at JSONPath.Object.<anonymous>.JSONPath._trace
    at JSONPath.Object.<anonymous>.JSONPath.evaluate

## Expected behavior

no error gets thrown, no results returned

## Environment (IMPORTANT)
- JSONPath-Plus version:v7.2.0

## Desktop**
 - NodeJS and browser

**Comment by brettz9** [comment]
In the json-path-comparison project, this does look like it should work per this example (which does indeed err in jsonpath-plus): https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_subpaths_deeply_nested.html

PRs welcome.

**Comment by 80avin** [comment]
There's an option [ignoreEvalErrors](https://github.com/JSONPath-Plus/JSONPath#:~:text=with%20context.%20%60%60-,ignoreEvalErrors,-(default%3A%20false) in version 9.0.0.

It was lacking documentation, to fix which I've created https://github.com/JSONPath-Plus/JSONPath/pull/219

**Comment by brettz9** [comment]
I think we need a change to default that to `true` given the cross-implementation behavior.

**Comment by Scratch-net** [comment]
Ignoring errors won't solve the problem though, wouldn't it?

**Comment by brettz9** [comment]
It should in fact fix it. The errors we are ignoring are those that err because they don't find any parent object. If we ignore those errors, jsonpath-plus can continue to find legitimate values (where the parent object does exist).

**Comment by Scratch-net** [comment]
Oh, that would be nice to try but there's no such property in `jsonpath.d.ts`

**Comment by brettz9** [comment]
As per https://github.com/JSONPath-Plus/JSONPath/issues/218#issuecomment-2383950924 , it was lacking docs. Just suppress the TS error for now; it's there.

**Comment by Scratch-net** [comment]
Yep, works. Thanks!
