### ISSUE TITLE
Does Running Node <18 break this?

### ISSUE THREAD

**Issue by sellomkantjwa** [JSONPath-Plus/JSONPath#227]
I'm ooking to upgrade from v7.2.0 to v10.0.0 but noticed that the minimum node version required is 18 (We're on 16). Is this because this was tested and found to not work on < 18 or is this just a natural update to move away from unmaintained node versions? I can take the risk it it's the latter but if there is something thats know to break on lesser node versions then we'd have to do the upgrade to 18 first.  

Thanks

**Comment by brettz9** [comment]
We've upgraded to make it easier to maintain code. We are now at least using `Object.hasOwn` which may break on earlier v16 versions, yes, but there could be other issues as well.

Closing but feel free to comment further as needed.
