### ISSUE TITLE
Fix the security problem in the old version like v9.0.1

### ISSUE THREAD

**Issue by DLillard0** [JSONPath-Plus/JSONPath#232]
I note that the security problem was fixed in the latest version, but the late version node required > 18.0.0 version, my project uses the 16.0.0 version now, so it is hard to upgrade to 18 😢 , can you fix the security problem in the old version like v9.0.1？

**Comment by brettz9** [comment]
While the fixes improve security, the work is still ongoing, and there may be other fixes still coming.

I would recommend using [nvm](https://github.com/nvm-sh/nvm) so that upgrading Node versions is not such a problem.

**Comment by DLillard0** [comment]
Thanks for your effort in fixing it 💪 .
I am using the nvm, and the reason for the difficulty in upgrading Node versions is some dependence in my project requires Node version < 18.0.0.

**Comment by brettz9** [comment]
I'm sorry, but I barely have energy as it is to maintain the project, and it gets too hard to maintain unsupported Node versions. Hope you find a way around your issue.
